# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        chmod +x ./build_app.sh
        # Modify the script to work non-interactively in CI
        sed -i '' 's/read -n 1 -r/echo "n"/g' ./build_app.sh
        ./build_app.sh
